"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.n5Words = void 0;
exports.n5Words = [
    { id: "n5-1", japanese: "会う", reading: "あう", meaning: "to meet", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-2", japanese: "青", reading: "あお", meaning: "blue", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-3", japanese: "青い", reading: "あおい", meaning: "blue", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-4", japanese: "赤", reading: "あか", meaning: "red", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-5", japanese: "赤い", reading: "あかい", meaning: "red", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-6", japanese: "明い", reading: "あかるい", meaning: "bright", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-7", japanese: "秋", reading: "あき", meaning: "autumn", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-8", japanese: "開く", reading: "あく", meaning: "to open, to become open", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-9", japanese: "開ける", reading: "あける", meaning: "to open", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-10", japanese: "上げる", reading: "あげる", meaning: "to give", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-11", japanese: "朝", reading: "あさ", meaning: "morning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-12", japanese: "朝御飯", reading: "あさごはん", meaning: "breakfast", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-14", japanese: "足", reading: "あし", meaning: "foot, leg", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-15", japanese: "明日", reading: "あした", meaning: "tomorrow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-17", japanese: "遊ぶ", reading: "あそぶ", meaning: "to play, to make a visit", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-18", japanese: "暖かい", reading: "あたたかい", meaning: "warm", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-19", japanese: "頭", reading: "あたま", meaning: "head", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-20", japanese: "新しい", reading: "あたらしい", meaning: "new", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-22", japanese: "暑い", reading: "あつい", meaning: "hot", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-23", japanese: "熱い", reading: "あつい", meaning: "hot to the touch", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-24", japanese: "厚い", reading: "あつい", meaning: "kind, deep, thick", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-26", japanese: "後", reading: "あと", meaning: "afterwards", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-28", japanese: "兄", reading: "あに", meaning: "(humble) older brother", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-29", japanese: "姉", reading: "あね", meaning: "(humble) older sister", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-34", japanese: "危ない", reading: "あぶない", meaning: "dangerous", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-35", japanese: "甘い", reading: "あまい", meaning: "sweet", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-37", japanese: "雨", reading: "あめ", meaning: "rain", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-38", japanese: "飴", reading: "あめ", meaning: "candy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-39", japanese: "洗う", reading: "あらう", meaning: "to wash", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-41", japanese: "歩く", reading: "あるく", meaning: "to walk", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-45", japanese: "言う", reading: "いう", meaning: "to say", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-46", japanese: "家", reading: "いえ", meaning: "house", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-48", japanese: "行く", reading: "いく", meaning: "to go", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-51", japanese: "池", reading: "いけ", meaning: "pond", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-52", japanese: "医者", reading: "いしゃ", meaning: "medical doctor", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-54", japanese: "忙しい", reading: "いそがしい", meaning: "busy, irritated", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-55", japanese: "痛い", reading: "いたい", meaning: "painful", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-56", japanese: "一", reading: "いち", meaning: "one", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-57", japanese: "一日", reading: "いちにち", meaning: "first of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-60", japanese: "五日", reading: "いつか", meaning: "five days, fifth day", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-61", japanese: "一緒", reading: "いっしょ", meaning: "together", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-62", japanese: "五つ", reading: "いつつ", meaning: "five", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-64", japanese: "犬", reading: "いぬ", meaning: "dog", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-65", japanese: "今", reading: "いま", meaning: "now", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-66", japanese: "意味", reading: "いみ", meaning: "meaning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-67", japanese: "妹", reading: "いもうと", meaning: "(humble) younger sister", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-68", japanese: "嫌", reading: "いや", meaning: "unpleasant", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-69", japanese: "入口", reading: "いりぐち", meaning: "entrance", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-70", japanese: "居る", reading: "いる", meaning: "to be, to have (used for people and animals)", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-71", japanese: "要る", reading: "いる", meaning: "to need", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-72", japanese: "入れる", reading: "いれる", meaning: "to put in", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-73", japanese: "色", reading: "いろ", meaning: "colour", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-75", japanese: "上", reading: "うえ", meaning: "on top of", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-76", japanese: "後ろ", reading: "うしろ", meaning: "behind", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-77", japanese: "薄い", reading: "うすい", meaning: "thin,weak", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-78", japanese: "歌", reading: "うた", meaning: "song", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-79", japanese: "歌う", reading: "うたう", meaning: "to sing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-80", japanese: "生まれる", reading: "うまれる", meaning: "to be born", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-81", japanese: "海", reading: "うみ", meaning: "sea", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-82", japanese: "売る", reading: "うる", meaning: "to sell", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-83", japanese: "煩い", reading: "うるさい", meaning: "noisy, annoying", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-84", japanese: "上着", reading: "うわぎ", meaning: "jacket", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-85", japanese: "絵", reading: "え", meaning: "picture", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-86", japanese: "映画", reading: "えいが", meaning: "movie", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-87", japanese: "映画館", reading: "えいがかん", meaning: "cinema", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-88", japanese: "英語", reading: "えいご", meaning: "English language", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-90", japanese: "駅", reading: "えき", meaning: "station", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-92", japanese: "鉛筆", reading: "えんぴつ", meaning: "pencil", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-94", japanese: "多い", reading: "おおい", meaning: "many", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-95", japanese: "大きい", reading: "おおきい", meaning: "big", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-96", japanese: "大きな", reading: "おおきな", meaning: "big", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-97", japanese: "大勢", reading: "おおぜい", meaning: "great number of people", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-98", japanese: "お母さん", reading: "おかあさん", meaning: "(honorable) mother", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-99", japanese: "お菓子", reading: "おかし", meaning: "sweets, candy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-100", japanese: "お金", reading: "おかね", meaning: "money", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-101", japanese: "起きる", reading: "おきる", meaning: "to get up", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-102", japanese: "置く", reading: "おく", meaning: "to put", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-103", japanese: "奥さん", reading: "おくさん", meaning: "(honorable) wife", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-104", japanese: "お酒", reading: "おさけ", meaning: "alcohol, rice wine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-105", japanese: "お皿", reading: "おさら", meaning: "plate, dish", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-106", japanese: "伯父/叔父", reading: "おじいさん", meaning: "grandfather, male senior citizen", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-107", japanese: "教える", reading: "おしえる", meaning: "to teach, to tell", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-108", japanese: "伯父/叔父", reading: "おじさん", meaning: "uncle, middle aged gentleman", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-109", japanese: "押す", reading: "おす", meaning: "to push, to stamp something", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-110", japanese: "遅い", reading: "おそい", meaning: "late, slow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-111", japanese: "お茶", reading: "おちゃ", meaning: "green tea", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-112", japanese: "お手洗い", reading: "おてあらい", meaning: "bathroom", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-113", japanese: "お父さん", reading: "おとうさん", meaning: "(honorable) father", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-114", japanese: "弟", reading: "おとうと", meaning: "younger brother", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-115", japanese: "男", reading: "おとこ", meaning: "Man", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-116", japanese: "男の子", reading: "おとこのこ", meaning: "Boy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-117", japanese: "一昨日", reading: "おととい", meaning: "day before yesterday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-118", japanese: "一昨年", reading: "おととし", meaning: "year before last", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-119", japanese: "大人", reading: "おとな", meaning: "Adult", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-121", japanese: "同じ", reading: "おなじ", meaning: "same", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-122", japanese: "お兄さん", reading: "おにいさん", meaning: "(honorable) older brother", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-123", japanese: "お姉さん", reading: "おねえさん", meaning: "(honorable) older sister", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-125", japanese: "伯母さん/叔母さん", reading: "おばさん", meaning: "Aunt", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-126", japanese: "お風呂", reading: "おふろ", meaning: "Bath", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-127", japanese: "お弁当", reading: "おべんとう", meaning: "boxed lunch", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-128", japanese: "覚える", reading: "おぼえる", meaning: "to remember", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-130", japanese: "重い", reading: "おもい", meaning: "Heavy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-132", japanese: "泳ぐ", reading: "およぐ", meaning: "to swim", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-133", japanese: "降りる", reading: "おりる", meaning: "to get off, to descend", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-134", japanese: "終る", reading: "おわる", meaning: "to finish", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-135", japanese: "音楽", reading: "おんがく", meaning: "Music", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-136", japanese: "女", reading: "おんな", meaning: "Woman", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-137", japanese: "女の子", reading: "おんなのこ", meaning: "Girl", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-138", japanese: "外国", reading: "がいこく", meaning: "foreign country", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-139", japanese: "外国人", reading: "がいこくじん", meaning: "Foreigner", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-140", japanese: "会社", reading: "かいしゃ", meaning: "Company", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-141", japanese: "階段", reading: "かいだん", meaning: "Stairs", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-142", japanese: "買い物", reading: "かいもの", meaning: "Shopping", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-143", japanese: "買う", reading: "かう", meaning: "to buy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-144", japanese: "返す", reading: "かえす", meaning: "to return something", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-145", japanese: "帰る", reading: "かえる", meaning: "to go back", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-148", japanese: "書く", reading: "かく", meaning: "to write", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-149", japanese: "学生", reading: "がくせい", meaning: "Student", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-151", japanese: "傘", reading: "かさ", meaning: "Umbrella", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-152", japanese: "貸す", reading: "かす", meaning: "to lend", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-153", japanese: "風", reading: "かぜ", meaning: "Wind", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-154", japanese: "風邪", reading: "かぜ", meaning: "a cold", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-155", japanese: "家族", reading: "かぞく", meaning: "Family", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-156", japanese: "方", reading: "かた", meaning: "person, way of doing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-157", japanese: "学校", reading: "がっこう", meaning: "School", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-159", japanese: "家庭", reading: "かてい", meaning: "Household", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-160", japanese: "角", reading: "かど", meaning: "a corner", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-162", japanese: "花瓶", reading: "かびん", meaning: "a vase", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-163", japanese: "紙", reading: "かみ", meaning: "paper", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-165", japanese: "火曜日", reading: "かようび", meaning: "Tuesday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-166", japanese: "辛い", reading: "からい", meaning: "Spicy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-167", japanese: "体", reading: "からだ", meaning: "Body", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-168", japanese: "借りる", reading: "かりる", meaning: "to borrow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-169", japanese: "軽い", reading: "かるい", meaning: "Light", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-172", japanese: "川/河", reading: "かわ", meaning: "River", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-174", japanese: "漢字", reading: "かんじ", meaning: "Chinese character", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-175", japanese: "木", reading: "き", meaning: "tree, wood", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-176", japanese: "黄色", reading: "きいろ", meaning: "yellow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-177", japanese: "黄色い", reading: "きいろい", meaning: "yellow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-178", japanese: "消える", reading: "きえる", meaning: "to disappear", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-179", japanese: "聞く", reading: "きく", meaning: "to hear, to listen to, to ask", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-180", japanese: "北", reading: "きた", meaning: "North", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-182", japanese: "汚い", reading: "きたない", meaning: "Dirty", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-183", japanese: "喫茶店", reading: "きっさてん", meaning: "coffee lounge", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-184", japanese: "切手", reading: "きって", meaning: "postage stamp", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-185", japanese: "切符", reading: "きっぷ", meaning: "Ticket", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-186", japanese: "昨日", reading: "きのう", meaning: "Yesterday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-187", japanese: "九", reading: "きゅう / く", meaning: "Nine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-188", japanese: "牛肉", reading: "ぎゅうにく", meaning: "Beef", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-189", japanese: "牛乳", reading: "ぎゅうにゅう", meaning: "Milk", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-190", japanese: "今日", reading: "きょう", meaning: "Today", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-191", japanese: "教室", reading: "きょうしつ", meaning: "Classroom", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-192", japanese: "兄弟", reading: "きょうだい", meaning: "(humble) siblings", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-193", japanese: "去年", reading: "きょねん", meaning: "last year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-194", japanese: "嫌い", reading: "きらい", meaning: "Hate", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-195", japanese: "切る", reading: "きる", meaning: "to cut", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-196", japanese: "着る", reading: "きる", meaning: "to put on from the shoulders down", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-200", japanese: "銀行", reading: "ぎんこう", meaning: "Bank", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-201", japanese: "金曜日", reading: "きんようび", meaning: "Friday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-202", japanese: "薬", reading: "くすり", meaning: "medicine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-204", japanese: "果物", reading: "くだもの", meaning: "Fruit", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-205", japanese: "口", reading: "くち", meaning: "mouth, opening", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-206", japanese: "靴", reading: "くつ", meaning: "Shoes", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-207", japanese: "靴下", reading: "くつした", meaning: "Socks", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-208", japanese: "国", reading: "くに", meaning: "Country", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-209", japanese: "曇り", reading: "くもり", meaning: "cloudy weather", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-210", japanese: "曇る", reading: "くもる", meaning: "to become cloudy, to become dim", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-211", japanese: "暗い", reading: "くらい", meaning: "Gloomy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-214", japanese: "来る", reading: "くる", meaning: "to come", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-215", japanese: "車", reading: "くるま", meaning: "car, vehicle", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-216", japanese: "黒", reading: "くろ", meaning: "Black", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-217", japanese: "黒い", reading: "くろい", meaning: "black", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-218", japanese: "警官", reading: "けいかん", meaning: "policeman", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-219", japanese: "今朝", reading: "けさ", meaning: "this morning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-220", japanese: "消す", reading: "けす", meaning: "to erase, to turn off power", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-221", japanese: "結構", reading: "けっこう", meaning: "splendid, enough", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-222", japanese: "結婚", reading: "けっこん", meaning: "Marriage", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-223", japanese: "月曜日", reading: "げつようび", meaning: "Monday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-224", japanese: "玄関", reading: "げんかん", meaning: "entry hall", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-225", japanese: "元気", reading: "げんき", meaning: "health, vitality", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-226", japanese: "五", reading: "ご", meaning: "Five", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-227", japanese: "公園", reading: "こうえん", meaning: "Park", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-228", japanese: "交差点", reading: "こうさてん", meaning: "intersection", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-229", japanese: "紅茶", reading: "こうちゃ", meaning: "black tea", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-230", japanese: "交番", reading: "こうばん", meaning: "police box", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-231", japanese: "声", reading: "こえ", meaning: "Voice", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-235", japanese: "午後", reading: "ごご", meaning: "afternoon", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-236", japanese: "九日", reading: "ここのか", meaning: "nine days, ninth day", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-237", japanese: "九つ", reading: "ここのつ", meaning: "Nine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-238", japanese: "午前", reading: "ごぜん", meaning: "morning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-239", japanese: "答える", reading: "こたえる", meaning: "to answer", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-243", japanese: "今年", reading: "ことし", meaning: "this year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-244", japanese: "言葉", reading: "ことば", meaning: "word, language", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-245", japanese: "子供", reading: "こども", meaning: "Child", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-247", japanese: "御飯", reading: "ごはん", meaning: "cooked rice, meal", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-249", japanese: "困る", reading: "こまる", meaning: "to be worried", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-251", japanese: "今月", reading: "こんげつ", meaning: "this month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-252", japanese: "今週", reading: "こんしゅう", meaning: "this week", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-254", japanese: "今晩", reading: "こんばん", meaning: "this evening", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-256", japanese: "財布", reading: "さいふ", meaning: "Wallet", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-257", japanese: "魚", reading: "さかな", meaning: "Fish", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-258", japanese: "先", reading: "さき", meaning: "the future, previous", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-259", japanese: "咲く", reading: "さく", meaning: "to bloom", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-260", japanese: "作文", reading: "さくぶん", meaning: "composition, writing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-261", japanese: "差す", reading: "さす", meaning: "to stretch out hands, to raise an umbrella", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-262", japanese: "雑誌", reading: "ざっし", meaning: "Magazine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-263", japanese: "砂糖", reading: "さとう", meaning: "Sugar", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-264", japanese: "寒い", reading: "さむい", meaning: "Cold", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-265", japanese: "さ来年", reading: "さらいねん", meaning: "year after next", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-266", japanese: "三", reading: "さん", meaning: "Three", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-267", japanese: "散歩", reading: "さんぽする", meaning: "to stroll", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-268", japanese: "四", reading: "し / よん", meaning: "Four", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-269", japanese: "塩", reading: "しお", meaning: "Salt", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-271", japanese: "時間", reading: "じかん", meaning: "Time", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-272", japanese: "仕事", reading: "しごと", meaning: "Job", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-273", japanese: "辞書", reading: "じしょ", meaning: "Dictionary", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-274", japanese: "静か", reading: "しずか", meaning: "Quiet", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-275", japanese: "下", reading: "した", meaning: "Below", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-276", japanese: "七", reading: "しち / なな", meaning: "Seven", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-277", japanese: "質問", reading: "しつもん", meaning: "Question", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-278", japanese: "自転車", reading: "じてんしゃ", meaning: "Bicycle", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-279", japanese: "自動車", reading: "じどうしゃ", meaning: "Automobile", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-280", japanese: "死ぬ", reading: "しぬ", meaning: "to die", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-281", japanese: "字引", reading: "じびき", meaning: "Dictionary", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-282", japanese: "自分", reading: "じぶん", meaning: "Oneself", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-283", japanese: "閉まる", reading: "しまる", meaning: "to close, to be closed", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-284", japanese: "閉める", reading: "しめる", meaning: "to close something", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-285", japanese: "締める", reading: "しめる", meaning: "to tie", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-287", japanese: "写真", reading: "しゃしん", meaning: "photograph", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-290", japanese: "十", reading: "じゅう とお", meaning: "Ten", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-291", japanese: "授業", reading: "じゅぎょう", meaning: "lesson, class work", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-292", japanese: "宿題", reading: "しゅくだい", meaning: "homework", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-293", japanese: "上手", reading: "じょうず", meaning: "Skillful", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-294", japanese: "丈夫", reading: "じょうぶ", meaning: "strong, durable", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-296", japanese: "食堂", reading: "しょくどう", meaning: "dining hall", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-297", japanese: "知る", reading: "しる", meaning: "to know", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-298", japanese: "白", reading: "しろ", meaning: "White", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-299", japanese: "白い", reading: "しろい", meaning: "White", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-300", japanese: "新聞", reading: "しんぶん", meaning: "newspaper", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-301", japanese: "水曜日", reading: "すいようび", meaning: "Wednesday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-302", japanese: "吸う", reading: "すう", meaning: "to smoke, to suck", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-304", japanese: "好き", reading: "すき", meaning: "Likeable", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-305", japanese: "少ない", reading: "すくない", meaning: "a few", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-307", japanese: "少し", reading: "すこし", meaning: "Few", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-308", japanese: "涼しい", reading: "すずしい", meaning: "Refreshing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-313", japanese: "住む", reading: "すむ", meaning: "to live in", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-316", japanese: "座る", reading: "すわる", meaning: "to sit", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-317", japanese: "背", reading: "せ", meaning: "height, stature", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-318", japanese: "生徒", reading: "せいと", meaning: "Pupil", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-321", japanese: "背広", reading: "せびろ", meaning: "business suit", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-322", japanese: "狭い", reading: "せまい", meaning: "Narrow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-324", japanese: "千", reading: "せん", meaning: "Thousand", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-325", japanese: "先月", reading: "せんげつ", meaning: "last month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-326", japanese: "先週", reading: "せんしゅう", meaning: "last week", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-327", japanese: "先生", reading: "せんせい", meaning: "teacher, doctor", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-328", japanese: "洗濯", reading: "せんたく", meaning: "Washing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-329", japanese: "全部", reading: "ぜんぶ", meaning: "All", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-330", japanese: "掃除", reading: "そうじする", meaning: "to clean, to sweep", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-335", japanese: "外", reading: "そと", meaning: "Outside", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-338", japanese: "空", reading: "そら", meaning: "Sky", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-342", japanese: "大学", reading: "だいがく", meaning: "university", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-343", japanese: "大使館", reading: "たいしかん", meaning: "embassy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-344", japanese: "大丈夫", reading: "だいじょうぶ", meaning: "all right", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-345", japanese: "大好き", reading: "だいすき", meaning: "to be very likeable", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-346", japanese: "大切", reading: "たいせつ", meaning: "important", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-347", japanese: "台所", reading: "だいどころ", meaning: "kitchen", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-350", japanese: "高い", reading: "たかい", meaning: "tall, expensive", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-353", japanese: "出す", reading: "だす", meaning: "to put out", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-354", japanese: "立つ", reading: "たつ", meaning: "to stand", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-356", japanese: "建物", reading: "たてもの", meaning: "building", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-357", japanese: "楽しい", reading: "たのしい", meaning: "enjoyable", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-358", japanese: "頼む", reading: "たのむ", meaning: "to ask", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-361", japanese: "食べ物", reading: "たべもの", meaning: "food", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-362", japanese: "食べる", reading: "たべる", meaning: "to eat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-363", japanese: "卵", reading: "たまご", meaning: "egg", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-364", japanese: "誰", reading: "だれ", meaning: "who", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-365", japanese: "誰", reading: "だれか", meaning: "somebody", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-366", japanese: "誕生日", reading: "たんじょうび", meaning: "birthday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-368", japanese: "小さい", reading: "ちいさい", meaning: "little", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-369", japanese: "小さな", reading: "ちいさな", meaning: "little", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-370", japanese: "近い", reading: "ちかい", meaning: "near", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-371", japanese: "違う", reading: "ちがう", meaning: "to differ", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-372", japanese: "近く", reading: "ちかく", meaning: "near", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-373", japanese: "地下鉄", reading: "ちかてつ", meaning: "underground train", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-374", japanese: "地図", reading: "ちず", meaning: "map", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-375", japanese: "茶色", reading: "ちゃいろ", meaning: "brown", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-379", japanese: "一日", reading: "ついたち", meaning: "first of month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-380", japanese: "使う", reading: "つかう", meaning: "to use", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-381", japanese: "疲れる", reading: "つかれる", meaning: "to get tired", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-382", japanese: "次", reading: "つぎ", meaning: "next", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-383", japanese: "着く", reading: "つく", meaning: "to arrive at", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-384", japanese: "机", reading: "つくえ", meaning: "desk", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-385", japanese: "作る", reading: "つくる", meaning: "to make", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-387", japanese: "勤める", reading: "つとめる", meaning: "to work for someone", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-389", japanese: "冷たい", reading: "つめたい", meaning: "cold to the touch", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-390", japanese: "強い", reading: "つよい", meaning: "powerful", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-391", japanese: "手", reading: "て", meaning: "hand", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-395", japanese: "出かける", reading: "でかける", meaning: "to go out", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-396", japanese: "手紙", reading: "てがみ", meaning: "letter", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-398", japanese: "出口", reading: "でぐち", meaning: "exit", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-403", japanese: "出る", reading: "でる", meaning: "to appear,to leave", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-405", japanese: "天気", reading: "てんき", meaning: "weather", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-406", japanese: "電気", reading: "でんき", meaning: "electricity,electric light", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-407", japanese: "電車", reading: "でんしゃ", meaning: "electric train", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-408", japanese: "電話", reading: "でんわ", meaning: "telephone", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-409", japanese: "戸", reading: "と", meaning: "Japanese style door", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-415", japanese: "動物", reading: "どうぶつ", meaning: "animal", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-417", japanese: "遠い", reading: "とおい", meaning: "far", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-418", japanese: "十日", reading: "とおか", meaning: "ten days,the tenth day", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-419", japanese: "時々", reading: "ときどき", meaning: "sometimes", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-420", japanese: "時計", reading: "とけい", meaning: "watch,clock", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-422", japanese: "所", reading: "ところ", meaning: "place", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-423", japanese: "年", reading: "とし", meaning: "year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-424", japanese: "図書館", reading: "としょかん", meaning: "library", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-429", japanese: "隣", reading: "となり", meaning: "next door to", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-431", japanese: "飛ぶ", reading: "とぶ", meaning: "to fly,to hop", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-432", japanese: "止まる", reading: "とまる", meaning: "to come to a halt", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-433", japanese: "友達", reading: "ともだち", meaning: "friend", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-434", japanese: "土曜日", reading: "どようび", meaning: "Saturday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-435", japanese: "鳥", reading: "とり", meaning: "bird", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-436", japanese: "とり肉", reading: "とりにく", meaning: "chicken meat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-437", japanese: "取る", reading: "とる", meaning: "to take something", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-438", japanese: "撮る", reading: "とる", meaning: "to take a photo or record a film", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-441", japanese: "中", reading: "なか", meaning: "middle", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-442", japanese: "長い", reading: "ながい", meaning: "long", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-443", japanese: "鳴く", reading: "なく", meaning: "animal noise. to chirp, roar or croak etc.", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-444", japanese: "無くす", reading: "なくす", meaning: "to lose something", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-446", japanese: "夏", reading: "なつ", meaning: "summer", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-447", japanese: "夏休み", reading: "なつやすみ", meaning: "summer holiday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-449", japanese: "七つ", reading: "ななつ", meaning: "seven", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-450", japanese: "七日", reading: "なのか", meaning: "seven days,the seventh day", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-451", japanese: "名前", reading: "なまえ", meaning: "name", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-452", japanese: "習う", reading: "ならう", meaning: "to learn", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-453", japanese: "並ぶ", reading: "ならぶ", meaning: "to line up,to stand in a line", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-454", japanese: "並べる", reading: "ならべる", meaning: "to line up,to set up", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-456", japanese: "何", reading: "なん/なに", meaning: "what", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-457", japanese: "二", reading: "に", meaning: "two", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-458", japanese: "賑やか", reading: "にぎやか", meaning: "bustling,busy", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-459", japanese: "肉", reading: "にく", meaning: "meat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-460", japanese: "西", reading: "にし", meaning: "west", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-461", japanese: "日曜日", reading: "にちようび", meaning: "Sunday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-462", japanese: "荷物", reading: "にもつ", meaning: "luggage", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-464", japanese: "庭", reading: "にわ", meaning: "garden", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-465", japanese: "脱ぐ", reading: "ぬぐ", meaning: "to take off clothes", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-466", japanese: "温い", reading: "ぬるい", meaning: "luke warm", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-468", japanese: "猫", reading: "ねこ", meaning: "cat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-469", japanese: "寝る", reading: "ねる", meaning: "to go to bed,to sleep", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-471", japanese: "登る", reading: "のぼる", meaning: "to climb", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-472", japanese: "飲み物", reading: "のみもの", meaning: "a drink", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-473", japanese: "飲む", reading: "のむ", meaning: "to drink", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-474", japanese: "乗る", reading: "のる", meaning: "to get on,to ride", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-475", japanese: "歯", reading: "は", meaning: "tooth", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-478", japanese: "灰皿", reading: "はいざら", meaning: "ashtray", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-479", japanese: "入る", reading: "はいる", meaning: "to enter,to contain", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-480", japanese: "葉書", reading: "はがき", meaning: "postcard", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-482", japanese: "箱", reading: "はこ", meaning: "box", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-483", japanese: "橋", reading: "はし", meaning: "bridge", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-485", japanese: "始まる", reading: "はじまる", meaning: "to begin", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-486", japanese: "初め/始め", reading: "はじめ", meaning: "beginning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-487", japanese: "初めて", reading: "はじめて", meaning: "for the first time", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-488", japanese: "走る", reading: "はしる", meaning: "to run", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-491", japanese: "二十歳", reading: "はたち", meaning: "20 years old,20th year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-492", japanese: "働く", reading: "はたらく", meaning: "to work", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-493", japanese: "八", reading: "はち", meaning: "eight", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-494", japanese: "二十日", reading: "はつか", meaning: "twenty days,twentieth", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-495", japanese: "花", reading: "はな", meaning: "flower", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-496", japanese: "鼻", reading: "はな", meaning: "nose", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-497", japanese: "話", reading: "はなし", meaning: "talk,story", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-498", japanese: "話す", reading: "はなす", meaning: "to speak", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-499", japanese: "早い", reading: "はやい", meaning: "early", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-500", japanese: "速い", reading: "はやい", meaning: "quick", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-501", japanese: "春", reading: "はる", meaning: "spring", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-502", japanese: "貼る", reading: "はる", meaning: "to stick", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-503", japanese: "晴れ", reading: "はれ", meaning: "clear weather", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-504", japanese: "晴れる", reading: "はれる", meaning: "to be sunny", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-505", japanese: "半", reading: "はん", meaning: "half", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-506", japanese: "晩", reading: "ばん", meaning: "evening", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-509", japanese: "番号", reading: "ばんごう", meaning: "number", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-510", japanese: "晩御飯", reading: "ばんごはん", meaning: "evening meal", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-511", japanese: "半分", reading: "はんぶん", meaning: "half minute", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-512", japanese: "東", reading: "ひがし", meaning: "east", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-513", japanese: "引く", reading: "ひく", meaning: "to pull", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-514", japanese: "弾く", reading: "ひく", meaning: "to play an instrument with strings, including piano", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-515", japanese: "低い", reading: "ひくい", meaning: "short,low", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-516", japanese: "飛行機", reading: "ひこうき", meaning: "aeroplane", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-517", japanese: "左", reading: "ひだり", meaning: "left hand side", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-518", japanese: "人", reading: "ひと", meaning: "person", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-519", japanese: "一つ", reading: "ひとつ", meaning: "one", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-520", japanese: "一月", reading: "ひとつき", meaning: "one month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-521", japanese: "一人", reading: "ひとり", meaning: "one person", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-522", japanese: "暇", reading: "ひま", meaning: "free time", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-523", japanese: "百", reading: "ひゃく", meaning: "hundred", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-524", japanese: "病院", reading: "びょういん", meaning: "hospital", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-525", japanese: "病気", reading: "びょうき", meaning: "illness", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-526", japanese: "昼", reading: "ひる", meaning: "noon, daytime", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-527", japanese: "昼御飯", reading: "ひるごはん", meaning: "midday meal", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-528", japanese: "広い", reading: "ひろい", meaning: "spacious,wide", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-530", japanese: "封筒", reading: "ふうとう", meaning: "envelope", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-533", japanese: "吹く", reading: "ふく", meaning: "to blow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-534", japanese: "服", reading: "ふく", meaning: "clothes", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-535", japanese: "二つ", reading: "ふたつ", meaning: "two", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-536", japanese: "豚肉", reading: "ぶたにく", meaning: "pork", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-537", japanese: "二人", reading: "ふたり", meaning: "two people", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-538", japanese: "二日", reading: "ふつか", meaning: "two days, second day of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-539", japanese: "太い", reading: "ふとい", meaning: "fat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-540", japanese: "冬", reading: "ふゆ", meaning: "winter", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-541", japanese: "降る", reading: "ふる", meaning: "to fall, e.g. rain or snow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-542", japanese: "古い", reading: "ふるい", meaning: "old (not used for people)", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-544", japanese: "文章", reading: "ぶんしょう", meaning: "sentence,text", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-546", japanese: "下手", reading: "へた", meaning: "unskillful", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-549", japanese: "部屋", reading: "へや", meaning: "room", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-550", japanese: "辺", reading: "へん", meaning: "area", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-552", japanese: "勉強", reading: "べんきょうする", meaning: "to study", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-553", japanese: "便利", reading: "べんり", meaning: "useful, convenient", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-554", japanese: "帽子", reading: "ぼうし", meaning: "hat", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-558", japanese: "欲しい", reading: "ほしい", meaning: "want", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-560", japanese: "細い", reading: "ほそい", meaning: "thin", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-563", japanese: "本", reading: "ほん", meaning: "book", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-564", japanese: "本棚", reading: "ほんだな", meaning: "bookshelves", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-566", japanese: "毎朝", reading: "まいあさ", meaning: "every morning", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-567", japanese: "毎月", reading: "まいげつ/まいつき", meaning: "every month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-568", japanese: "毎週", reading: "まいしゅう", meaning: "every week", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-569", japanese: "毎日", reading: "まいにち", meaning: "every day", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-570", japanese: "毎年", reading: "まいねん/まいとし", meaning: "every year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-571", japanese: "毎晩", reading: "まいばん", meaning: "every night", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-572", japanese: "前", reading: "まえ", meaning: "before", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-573", japanese: "曲る", reading: "まがる", meaning: "to turn,to bend", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-577", japanese: "町", reading: "まち", meaning: "town,city", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-578", japanese: "待つ", reading: "まつ", meaning: "to wait", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-581", japanese: "窓", reading: "まど", meaning: "window", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-582", japanese: "丸い/円い", reading: "まるい", meaning: "round,circular", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-583", japanese: "万", reading: "まん", meaning: "ten thousand", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-584", japanese: "万年筆", reading: "まんねんひつ", meaning: "fountain pen", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-585", japanese: "磨く", reading: "みがく", meaning: "to brush teeth, to polish", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-586", japanese: "右", reading: "みぎ", meaning: "right side", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-587", japanese: "短い", reading: "みじかい", meaning: "short", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-588", japanese: "水", reading: "みず", meaning: "water", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-589", japanese: "店", reading: "みせ", meaning: "shop", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-590", japanese: "見せる", reading: "みせる", meaning: "to show", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-591", japanese: "道", reading: "みち", meaning: "street", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-592", japanese: "三日", reading: "みっか", meaning: "three days, third day of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-593", japanese: "三つ", reading: "みっつ", meaning: "three", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-594", japanese: "緑", reading: "みどり", meaning: "green", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-595", japanese: "皆さん", reading: "みなさん", meaning: "everyone", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-596", japanese: "南", reading: "みなみ", meaning: "south", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-597", japanese: "耳", reading: "みみ", meaning: "ear", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-598", japanese: "見る 観る", reading: "みる", meaning: "to see, to watch", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-600", japanese: "六日", reading: "むいか", meaning: "six days, sixth day of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-601", japanese: "向こう", reading: "むこう", meaning: "over there", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-602", japanese: "難しい", reading: "むずかしい", meaning: "difficult", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-603", japanese: "六つ", reading: "むっつ", meaning: "six", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-604", japanese: "村", reading: "むら", meaning: "village", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-605", japanese: "目", reading: "め", meaning: "eye", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-607", japanese: "眼鏡", reading: "めがね", meaning: "glasses", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-609", japanese: "もう一度", reading: "もういちど", meaning: "again", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-610", japanese: "木曜日", reading: "もくようび", meaning: "Thursday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-611", japanese: "持つ", reading: "もつ", meaning: "to hold", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-613", japanese: "物", reading: "もの", meaning: "thing", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-614", japanese: "門", reading: "もん", meaning: "gate", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-615", japanese: "問題", reading: "もんだい", meaning: "problem", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-616", japanese: "八百屋", reading: "やおや", meaning: "greengrocer", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-617", japanese: "野菜", reading: "やさい", meaning: "vegetable", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-618", japanese: "易しい", reading: "やさしい", meaning: "easy, simple", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-619", japanese: "安い", reading: "やすい", meaning: "cheap", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-620", japanese: "休み", reading: "やすみ", meaning: "rest,holiday", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-621", japanese: "休む", reading: "やすむ", meaning: "to rest", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-622", japanese: "八つ", reading: "やっつ", meaning: "eight", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-623", japanese: "山", reading: "やま", meaning: "mountain", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-625", japanese: "夕方", reading: "ゆうがた", meaning: "evening", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-626", japanese: "夕飯", reading: "ゆうはん", meaning: "dinner", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-627", japanese: "郵便局", reading: "ゆうびんきょく", meaning: "post office", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-628", japanese: "昨夜", reading: "ゆうべ", meaning: "last night", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-629", japanese: "有名", reading: "ゆうめい", meaning: "famous", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-630", japanese: "雪", reading: "ゆき", meaning: "snow", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-631", japanese: "行く", reading: "ゆく", meaning: "to go", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-633", japanese: "八日", reading: "ようか", meaning: "eight days, eighth day of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-634", japanese: "洋服", reading: "ようふく", meaning: "western-style clothes", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-636", japanese: "横", reading: "よこ", meaning: "beside,side,width", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-637", japanese: "四日", reading: "よっか", meaning: "four days, fouth day of the month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-638", japanese: "四つ", reading: "よっつ", meaning: "four", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-639", japanese: "呼ぶ", reading: "よぶ", meaning: "to call out,to invite", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-640", japanese: "読む", reading: "よむ", meaning: "to read", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-641", japanese: "夜", reading: "よる", meaning: "evening,night", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-642", japanese: "弱い", reading: "よわい", meaning: "weak", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-643", japanese: "来月", reading: "らいげつ", meaning: "next month", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-644", japanese: "来週", reading: "らいしゅう", meaning: "next week", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-645", japanese: "来年", reading: "らいねん", meaning: "next year", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-649", japanese: "留学生", reading: "りゅうがくせい", meaning: "overseas student", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-650", japanese: "両親", reading: "りょうしん", meaning: "both parents", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-651", japanese: "料理", reading: "りょうり", meaning: "cuisine", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-652", japanese: "旅行", reading: "りょこう", meaning: "travel", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-653", japanese: "零", reading: "れい", meaning: "zero", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-654", japanese: "冷蔵庫", reading: "れいぞうこ", meaning: "refrigerator", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-657", japanese: "練習", reading: "れんしゅうする", meaning: "to practice", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-658", japanese: "廊下", reading: "ろうか", meaning: "corridor", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-659", japanese: "六", reading: "ろく", meaning: "six", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-661", japanese: "若い", reading: "わかい", meaning: "young", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-662", japanese: "分かる", reading: "わかる", meaning: "to be understood", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-663", japanese: "忘れる", reading: "わすれる", meaning: "to forget", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-664", japanese: "私", reading: "わたくし", meaning: "(humble) I,myself", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-665", japanese: "私", reading: "わたし", meaning: "I,myself", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-666", japanese: "渡す", reading: "わたす", meaning: "to hand over", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-667", japanese: "渡る", reading: "わたる", meaning: "to go across", deckId: "jlpt-n5", jlpt: "N5" },
    { id: "n5-668", japanese: "悪い", reading: "わるい", meaning: "bad", deckId: "jlpt-n5", jlpt: "N5" }
];
